const copy = {
  ru: {
    demo: 'Демо для судей', demoTitle: 'Демонстрация графиков',
    demoHelp: 'Без ESP32 и сервера. Нажмите «Начать запись», чтобы увидеть четыре тестовых отведения.',
    demoNote: 'Искусственный сигнал · 72 уд/мин · не запись пациента. Диагностический анализ не выполняется, данные не сохраняются в историю.',
    demoSignal: 'Тестовый сигнал · условные единицы',
    title: 'Ритм под наблюдением', subtitle: 'Четыре отведения. Непрерывная запись.',
    workspace: 'РАБОЧЕЕ ПРОСТРАНСТВО', monitor: 'Монитор ЭКГ', connection: 'Подключение',
    session: 'Текущая запись', duration: 'Длительность', frames: 'Измерения', rate: 'Частота измерений',
    losses: 'Пропуски кадров', queue: 'Потери очереди платы', ready: 'Готов к записи', waiting: 'Ожидание сигнала',
    receiving: 'Идёт запись', finished: 'Запись завершена', server: 'Сервис приложения', device: 'Устройство',
    online: 'Доступен', offline: 'Недоступен', connected: 'Подключено', disconnected: 'Не подключено',
    network: 'Сеть устройства', password: 'Пароль', connectHelp: 'Подключите компьютер к сети платы, затем начните запись.',
    legacy: 'USB требует прошивку с передачей ЭКГ через последовательный порт. Текущая прошивка выводит по USB только диагностику.',
    guide: 'Как подключить', history: 'История записей', start: 'Начать запись', stop: 'Завершить запись',
    chart: 'Сигнал в реальном времени', window: 'Окно', seconds: 'с', samples: 'отсчётов',
    auto: 'Автомасштаб', common: 'Общий масштаб', scale: 'Масштаб', pause: 'Заморозить график', resume: 'Продолжить график',
    frozen: 'График заморожен · запись продолжается', raw: 'Исходные значения АЦП · без калибровки в мВ',
    measured: 'Измеряемое', derived: 'Вычисляемое', empty: 'Сигнал появится после подключения платы и начала записи',
    noData: 'Нет данных', ai: 'После первых 10 секунд модель обновляет анализ I, II и III каждые 2 секунды во время записи. Опросник не требуется. V1 отображается и сохраняется отдельно.',
    footer: 'ADS1293 / ESP32 · I, II, III, V1', saved: 'Запись идёт до остановки или отключения устройства. Вся запись сохраняется в истории; окно графика не ограничивает её длительность.',
    guideTitle: 'От подключения до первой ЭКГ', guideSubtitle: 'Инструкция для текущей конфигурации ADS1293 + ESP32.',
    quick: 'Быстрый старт', wiring: 'Схема подключения', wiringSub: 'Пять электродов → три измеряемых канала → четыре отведения.',
    electrodeRoles: 'На теле пять электродов: RA (правая рука), LA (левая рука), LL (левая нога), RL (правая нога) и грудной V1. RA, LA, LL и V1 участвуют в измерении сигнала. RL подключён к RLD для подавления синфазной помехи. Три канала измерения не означают три сигнальных электрода: каждый канал измеряет разность потенциалов.',
    wiringSource: 'Схема TI: пять электродов, рис. 86 (стр. 65)',
    placementTitle: 'Размещение пяти электродов на туловище',
    placementAlt: 'Схема ProtoCentral: RA и LA под ключицами, RL и LL внизу живота, грудной V1; два кабеля к плате ADS1293.',
    placementNote: 'Вариант Mason–Likar: RA — под правой ключицей, LA — под левой, RL — справа внизу живота, LL — слева внизу. V1 — четвёртое межреберье у правого края грудины. Право и лево указаны со стороны человека; рисунок схематичный. Нажмите, чтобы увеличить.',
    cableColorNote: 'Цвета и разъёмы CON1/CON2 на рисунке относятся к кабелям ProtoCentral. Красный, жёлтый и зелёный провода другого кабеля нельзя сопоставить по этой картинке. Нужна подтверждённая распиновка «провод → контакт штекера → вход платы»; прозвонку выполняют при отключённом питании и без электродов на человеке. Для текущей прошивки соответствие входов приведено ниже; IN6 остаётся изолированным.',
    placementSource: 'Источник изображения: ProtoCentral',
    mapping: 'Входы ADS1293', leads: 'Как формируются отведения', faq: 'Если что-то не работает',
    step1: 'Подготовьте устройство', step1body: 'Используйте текущую прошивку ADS1293. После запуска ESP32 создаёт собственную WiFi-сеть.',
    step2: 'Подключитесь к WiFi', step2body: 'На компьютере выберите CardioScan-ESP32. Пароль: 12345678. Отсутствие интернета в этой сети не мешает локальной записи.',
    step3: 'Откройте монитор', step3body: 'Запустите локальный сервис приложения. Откройте «Монитор ЭКГ» и оставьте режим WiFi.',
    step4: 'Запишите сигнал', step4body: 'Нажмите «Начать запись». Проверьте I, II, III и V1. Запись продолжается до завершения или отключения; все принятые измерения сохраняются в истории.',
    wiringNote: 'WCT = (RA + LA + LL) / 3 — внутренняя опора Wilson на IN6, а не шестой электрод. IN6 к телу не подключается; конец кабеля остаётся изолированным. CH3 измеряет V1 относительно WCT. Обозначения входов не определяют цвета проводов или распиновку разъёма модуля.',
    q1: 'Почему графики пустые?', a1: 'Проверьте сеть CardioScan-ESP32, доступность сервиса приложения и начало записи. ESP32 должен передавать данные на TCP-порту 3333. Сообщения в USB-мониторе сами по себе не означают, что ЭКГ поступает.',
    q2: 'Почему нет сигнала через USB?', a2: 'Текущая прошивка передаёт ЭКГ по WiFi/TCP. USB выводит диагностику. Для записи по USB нужна прошивка с передачей отсчётов через последовательный порт.',
    q3: 'Что означает частота на экране?', a3: 'Это оценка частоты измерений по временным меткам и номерам кадров. Она появляется примерно через секунду. Частота SPI 1–4 МГц относится к обмену между микросхемой и ESP32.',
    q4: 'Почему III отличается от I и II?', a4: 'III вычисляется прошивкой как II − I. Это отдельное отведение, но не третий независимо измеряемый канал. Автомасштаб подбирается отдельно для каждого графика; общий масштаб позволяет сравнить размах.',
    q5: 'Что анализирует AI?', a5: 'Модель потока использует последние 10 секунд I, II и III. V1 отображается и сохраняется, но не подаётся в эту модель. Фото обрабатывает прежняя отдельная модель. Длительность записи не ограничена окном анализа.',
  },
  en: {
    demo: 'Judges’ demo', demoTitle: 'Waveform demonstration',
    demoHelp: 'No ESP32 or server needed. Press “Start recording” to view four test leads.',
    demoNote: 'Generated signal · 72 bpm · not a patient recording. No diagnostic analysis or history entry is produced.',
    demoSignal: 'Test signal · arbitrary units',
    title: 'A closer look at every beat', subtitle: 'Four leads. Continuous recording.', workspace: 'WORKSPACE',
    monitor: 'ECG monitor', connection: 'Connection', session: 'Current recording', duration: 'Duration', frames: 'Measurements', rate: 'Sample rate',
    losses: 'Sequence gaps', queue: 'Device queue losses', ready: 'Ready to record', waiting: 'Waiting for signal', receiving: 'Recording', finished: 'Recording complete',
    server: 'App service', device: 'Device', online: 'Available', offline: 'Unavailable', connected: 'Connected', disconnected: 'Disconnected',
    network: 'Device network', password: 'Password', connectHelp: 'Connect your computer to the device network, then start recording.',
    legacy: 'USB requires firmware that streams ECG over a serial port. Current firmware sends only diagnostics over USB.', guide: 'Connection guide', history: 'Recording history',
    start: 'Start recording', stop: 'Finish recording', chart: 'Live signal', window: 'Window', seconds: 's', samples: 'samples',
    auto: 'Auto scale', common: 'Shared scale', scale: 'Scale', pause: 'Freeze chart', resume: 'Resume chart', frozen: 'Chart frozen · recording continues',
    raw: 'Raw ADC values · not calibrated in mV', measured: 'Measured', derived: 'Derived', empty: 'Connect your device and start recording to see the signal',
    noData: 'No data', ai: 'After the first 10 seconds, the model updates the I, II and III analysis every 2 seconds during recording. No questionnaire is required. V1 is displayed and saved separately.', footer: 'ADS1293 / ESP32 · I, II, III, V1', saved: 'Recording continues until stopped or disconnected. The entire recording is saved to history; the chart window does not limit its duration.',
    guideTitle: 'From connection to your first ECG', guideSubtitle: 'A guide to the current ADS1293 + ESP32 configuration.',
    quick: 'Quick start', wiring: 'Connection diagram', wiringSub: 'Five electrodes → three measured channels → four leads.', mapping: 'ADS1293 inputs', leads: 'How the leads are formed', faq: 'Troubleshooting',
    electrodeRoles: 'Five body electrodes: RA (right arm), LA (left arm), LL (left leg), RL (right leg) and chest V1. RA, LA, LL and V1 participate in signal measurement. RL connects to RLD to suppress common-mode interference. Three measurement channels do not mean three sensing electrodes: each channel measures a potential difference.',
    wiringSource: 'TI five-electrode diagram: figure 86 (page 65)',
    placementTitle: 'Five-electrode torso placement',
    placementAlt: 'ProtoCentral diagram: RA and LA below the collarbones, RL and LL on the lower abdomen, chest V1, and two cables to ADS1293.',
    placementNote: 'Mason–Likar placement: RA below the right collarbone, LA below the left, RL on the lower right abdomen and LL on the lower left. V1: fourth intercostal space at the right sternal border. Right and left refer to the person; the drawing is schematic. Click to enlarge.',
    cableColorNote: 'Colors and CON1/CON2 connectors shown belong to ProtoCentral cables. Red, yellow and green wires on another cable cannot be mapped from this image. Verify the wire → plug contact → board input mapping; continuity checks require power disconnected and no electrodes attached to a person. The current firmware input mapping is below; IN6 stays insulated.',
    placementSource: 'Image source: ProtoCentral',
    step1: 'Prepare the device', step1body: 'Use the current ADS1293 firmware. ESP32 creates its own WiFi network on startup.',
    step2: 'Connect to WiFi', step2body: 'Select CardioScan-ESP32 on your computer. Password: 12345678. Internet access is not needed for local recording.',
    step3: 'Open the monitor', step3body: 'Start the local app service. Open the ECG monitor and select WiFi.',
    step4: 'Record the signal', step4body: 'Start recording and check I, II, III and V1. Recording continues until stopped or disconnected; all received samples are saved to history.',
    wiringNote: 'WCT = (RA + LA + LL) / 3 is the internal Wilson reference on IN6, not a sixth electrode. Do not connect IN6 to the body; leave its cable end insulated. CH3 measures V1 against WCT. Input labels do not specify wire colors or the module connector pinout.',
    q1: 'Why are the charts empty?', a1: 'Check the CardioScan-ESP32 network, app service and recording state. ESP32 must stream on TCP port 3333. USB diagnostic messages do not confirm ECG reception.',
    q2: 'Why is there no ECG over USB?', a2: 'Current firmware streams ECG over WiFi/TCP. USB is for diagnostics. USB recording requires firmware that streams samples over serial.',
    q3: 'What does the displayed rate mean?', a3: 'It estimates measurements per second from timestamps and sequence numbers, after about one second. The 1–4 MHz SPI clock is for communication between the chip and ESP32.',
    q4: 'Why is lead III different?', a4: 'Firmware derives III as II − I. It is not a third independently measured channel. Auto scale adjusts each trace separately; shared scale helps compare their amplitudes.',
    q5: 'What does AI analyze?', a5: 'The stream model uses the last 10 seconds of I, II and III. V1 is displayed and saved but is not supplied to this model. Photos use the existing separate model. The analysis window does not limit recording duration.',
  },
  kz: {
    demo: 'Қазыларға демо', demoTitle: 'Графиктерді көрсету',
    demoHelp: 'ESP32 және сервер қажет емес. Төрт сынақ тіркемесін көру үшін жазуды бастаңыз.',
    demoNote: 'Жасанды сигнал · 72 соққы/мин · пациент жазбасы емес. Диагностикалық талдау орындалмайды, тарихқа сақталмайды.',
    demoSignal: 'Сынақ сигналы · шартты бірліктер',
    title: 'Жүрек ырғағын бақылау', subtitle: 'Төрт тіркеме. Үздіксіз жазба.', workspace: 'ЖҰМЫС КЕҢІСТІГІ', monitor: 'ЭКГ мониторы',
    connection: 'Қосылым', session: 'Ағымдағы жазба', duration: 'Ұзақтығы', frames: 'Өлшемдер', rate: 'Өлшеу жиілігі', losses: 'Кадр үзілістері', queue: 'Тақша кезегіндегі жоғалтулар',
    ready: 'Жазуға дайын', waiting: 'Сигнал күтілуде', receiving: 'Жазылуда', finished: 'Жазба аяқталды', server: 'Қолданба қызметі', device: 'Құрылғы',
    online: 'Қолжетімді', offline: 'Қолжетімсіз', connected: 'Қосылған', disconnected: 'Қосылмаған', network: 'Құрылғы желісі', password: 'Құпиясөз',
    connectHelp: 'Компьютерді тақша желісіне қосып, жазуды бастаңыз.', legacy: 'USB арқылы ЭКГ жазу үшін сериялық деректерді жіберетін бағдарлама қажет. Ағымдағы бағдарлама USB арқылы тек диагностиканы шығарады.',
    guide: 'Қосу нұсқаулығы', history: 'Жазбалар тарихы', start: 'Жазуды бастау', stop: 'Жазуды аяқтау', chart: 'Нақты уақыттағы сигнал', window: 'Терезе', seconds: 'с', samples: 'өлшем',
    auto: 'Автомасштаб', common: 'Ортақ масштаб', scale: 'Масштаб', pause: 'Графикті тоқтату', resume: 'Графикті жалғастыру', frozen: 'График тоқтатылды · жазу жалғасуда',
    raw: 'АЦП бастапқы мәндері · мВ-қа калибрленбеген', measured: 'Өлшенген', derived: 'Есептелген', empty: 'Сигналды көру үшін құрылғыны қосып, жазуды бастаңыз',
    noData: 'Деректер жоқ', ai: 'Алғашқы 10 секундтан кейін I, II және III талдауы жазу кезінде әр 2 секунд сайын жаңарады. Сауалнама қажет емес. V1 бөлек көрсетіліп, сақталады.', footer: 'ADS1293 / ESP32 · I, II, III, V1', saved: 'Жазу тоқтатылғанша немесе құрылғы ажыратылғанша жалғасады. Барлық жазба тарихта сақталады; график терезесі жазба ұзақтығын шектемейді.',
    guideTitle: 'Қосылымнан алғашқы ЭКГ-ға дейін', guideSubtitle: 'ADS1293 + ESP32 ағымдағы конфигурациясына арналған нұсқаулық.', quick: 'Жылдам бастау', wiring: 'Қосылу сызбасы',
    wiringSub: 'Бес электрод → үш өлшенген арна → төрт тіркеме.', mapping: 'ADS1293 кірістері', leads: 'Тіркемелердің қалыптасуы', faq: 'Ақауларды анықтау',
    electrodeRoles: 'Денеде бес электрод: RA (оң қол), LA (сол қол), LL (сол аяқ), RL (оң аяқ) және кеуделік V1. RA, LA, LL және V1 сигналды өлшеуге қатысады. RL синфазалық кедергіні басу үшін RLD-ге қосылады. Үш өлшеу арнасы үш сигналдық электродты білдірмейді: әр арна потенциалдар айырмасын өлшейді.',
    wiringSource: 'TI бес электрод сызбасы: 86-сурет (65-бет)',
    placementTitle: 'Бес электродты денеге орналастыру',
    placementAlt: 'ProtoCentral сызбасы: RA және LA бұғаналар астында, RL және LL іштің төменгі бөлігінде, кеуделік V1 және ADS1293-ке екі кабель.',
    placementNote: 'Mason–Likar: RA — оң бұғана астында, LA — сол бұғана астында, RL — іштің төменгі оң жағында, LL — төменгі сол жағында. V1 — төстің оң жиегіндегі төртінші қабырғааралықта. Оң және сол жақ адамның өзіне қатысты; сурет сызбалық түрде берілген. Үлкейту үшін басыңыз.',
    cableColorNote: 'Суреттегі түстер мен CON1/CON2 қосқыштары ProtoCentral кабельдеріне тиесілі. Басқа кабельдің қызыл, сары және жасыл сымдарын осы суретпен сәйкестендіруге болмайды. «Сым → штекер түйіспесі → тақша кірісі» сәйкестігін тексеру керек; тұтастықты тексеру қуат өшірілгенде және адамға электродтар қосылмаған кезде орындалады. Ағымдағы бағдарлама кірістерінің сәйкестігі төменде берілген; IN6 оқшауланған күйде қалады.',
    placementSource: 'Сурет көзі: ProtoCentral',
    step1: 'Құрылғыны дайындаңыз', step1body: 'Ағымдағы ADS1293 бағдарламасын қолданыңыз. ESP32 іске қосылғанда өз WiFi желісін құрады.',
    step2: 'WiFi желісіне қосылыңыз', step2body: 'Компьютерде CardioScan-ESP32 желісін таңдаңыз. Құпиясөз: 12345678. Жергілікті жазбаға интернет қажет емес.',
    step3: 'Мониторды ашыңыз', step3body: 'Қолданбаның жергілікті қызметін іске қосыңыз. ЭКГ мониторын ашып, WiFi режимін таңдаңыз.',
    step4: 'Сигналды жазыңыз', step4body: 'Жазуды бастап, I, II, III және V1 тіркемелерін тексеріңіз. Жазу тоқтатылғанша немесе құрылғы ажыратылғанша жалғасады; барлық өлшемдер тарихта сақталады.',
    wiringNote: 'WCT = (RA + LA + LL) / 3 — IN6 ішкі Wilson тірегі, алтыншы электрод емес. IN6 денеге қосылмайды; кабель ұшы оқшауланады. CH3 WCT-ге қатысты V1 өлшейді. Кіріс белгілері сым түстерін немесе модуль қосқышының түйіспелерін анықтамайды.',
    q1: 'Графиктер неге бос?', a1: 'CardioScan-ESP32 желісін, қолданба қызметін және жазудың басталғанын тексеріңіз. ESP32 TCP 3333 порты арқылы дерек жіберуі керек.',
    q2: 'USB арқылы ЭКГ неге жоқ?', a2: 'Ағымдағы бағдарлама ЭКГ-ны WiFi/TCP арқылы жібереді. USB диагностикаға арналған. USB жазбасы үшін сериялық өлшемдерді жіберетін бағдарлама қажет.',
    q3: 'Экрандағы жиілік нені білдіреді?', a3: 'Уақыт белгілері мен кадр нөмірлері бойынша өлшеу жиілігін шамамен бір секундтан кейін есептейді. SPI 1–4 МГц — микросхема мен ESP32 арасындағы байланыс жиілігі.',
    q4: 'III тіркеме неге өзгеше?', a4: 'III = II − I формуласы бойынша есептеледі. Бұл үшінші тәуелсіз өлшенген арна емес. Автомасштаб әр графикке бөлек қолданылады; ортақ масштаб амплитудаларды салыстырады.',
    q5: 'AI нені талдайды?', a5: 'Модель I, II және III тіркемелерінің соңғы 10 секундын қолданады. V1 көрсетіліп, сақталады, бірақ модельге берілмейді. Фотоларды бұрынғы бөлек модель өңдейді. Талдау терезесі жазба ұзақтығын шектемейді.',
  },
}

export const monitorCopy = lang => copy[lang] ?? copy.en
